### ISSUE TITLE
Uncaught TypeError when closing second view of an open file

### ISSUE THREAD

**Issue by bobsoap** [forivall/atom-remember-folds#6]
Error: Uncaught TypeError: Cannot read property 'foldsMarkerLayer' of undefined

How to reproduce:
1. Open a file
2. Right-click in the active pane and select Split Right (or Up/Down/Left). This will duplicate the open file in a new pane.
3. Close one of the two views of the same file.

Thank you for making this necessary, great addon!

**Comment by viion** [comment]
I also get this, been getting it a lot recently. I think it might be to do with the new pane setup in Atom 1.9+

```
Uncaught TypeError: Cannot read property 'foldsMarkerLayer' of undefined
/Users/joshfreeman/.atom/packages/remember-folds/lib/remember-folds.js:47
Hide Stack Trace
TypeError: Cannot read property 'foldsMarkerLayer' of undefined
    at Object.onCloseTextEditor (/Users/joshfreeman/.atom/packages/remember-folds/lib/remember-folds.js:47:59)
    at /Users/joshfreeman/.atom/packages/remember-folds/lib/remember-folds.js:31:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.didDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:302:27)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:578:17)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:639:16)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:619:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:707:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:746:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:217:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by forivall** [comment]
Yup, this happened to me, though I didn't know how to replicate it at the time. Thanks for the info, now I'll know if https://github.com/forivall/atom-remember-folds/commit/7e07f39b9a5ca7aa6c1f1ee19426d0e0dd29e4d9 fixed it. I'll publish a new release soonish.

**Comment by forivall** [comment]
New version released. See if it works!
