### ISSUE TITLE
Uncaught TypeError: Cannot read property 'foldsMarkerLayer' of undefined

### ISSUE THREAD

**Issue by zenopopovici** [forivall/atom-remember-folds#7]
[Enter steps to reproduce below:]

1. Close file
2. ...

**Atom Version**: 1.9.9
**System**: Mac OS X 10.12
**Thrown From**: [remember-folds](https://github.com/forivall/atom-remember-folds) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'foldsMarkerLayer' of undefined

```
At /Users/Zeno/.atom/packages/remember-folds/lib/remember-folds.js:47

TypeError: Cannot read property 'foldsMarkerLayer' of undefined
    at Object.onCloseTextEditor (/Users/Zeno/.atom/packages/remember-folds/lib/remember-folds.js:47:59)
    at /Users/Zeno/.atom/packages/remember-folds/lib/remember-folds.js:31:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.didDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:302:27)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:578:17)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:639:16)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:619:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:707:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:746:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:217:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -7:52.5.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -6:38.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:36.4.0 core:save (atom-text-editor.editor.is-focused)
  4x -6:25.5.0 core:undo (atom-text-editor.editor.is-focused)
     -6:23.6.0 core:save (atom-text-editor.editor.is-focused)
     -6:13.7.0 core:close (atom-text-editor.editor.is-focused)
     -3:14.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:27.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "language-csharp",
      "language-clojure",
      "language-c",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-xml",
      "language-yaml",
      "language-toml",
      "alignment",
      "todo-list",
      "todo-list",
      "symbols-tree-view",
      "package-generator",
      "SFTP-deployment",
      "atom-ftp-editor",
      "welcome",
      "timecop",
      "styleguide",
      "auto-update-packages",
      "linter-tidy",
      "tab-close",
      "close-on-left",
      "tag",
      "imdone-atom",
      "synced-sidebar",
      "nuclide",
      "auto-replace-in-selection",
      "activate-power-mode",
      "w3c-validation",
      "npm-outdated",
      "linter-jslint",
      "autocomplete-project-paths",
      "disable-grammars",
      "goto",
      "linter-htmlhint"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      ".gitignore",
      "bower_components",
      "node_modules"
    ],
    "packagesWithKeymapsDisabled": [
      ""
    ],
    "projectHome": "/Users/Zeno/Sites"
  }
}
```

### Installed Packages

```coffee
# User
acf-snippets, v0.6.2 (inactive)
atom-alignment, v0.12.1 (active)
atom-beautify, v0.29.11 (active)
atom-numbers, v0.7.0 (active)
atom-terminal, v0.8.0 (inactive)
atom-wrap-in-tag, v0.6.0 (inactive)
auto-update-packages, v1.0.1 (inactive)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-nunjucks, v0.5.0 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-wordpress-hooks, v0.2.0 (active)
change-case, v0.6.3 (active)
clipboard-plus, v0.5.1 (active)
copy-filename, v1.0.1 (active)
define-jump, v1.0.1 (inactive)
docblockr, v0.8.4 (active)
double-tag, v0.4.0 (active)
editorconfig, v1.4.1 (active)
emmet, v2.4.3 (active)
escape-utils, v0.5.3 (inactive)
file-type-icons, v1.3.2 (active)
filesize, v0.4.2 (active)
git-blame, v0.4.11 (inactive)
git-history, v3.2.0 (inactive)
git-projects, v1.17.0 (inactive)
highlight-selected, v0.11.2 (active)
indent-toggle-on-paste, v0.1.3 (inactive)
keybinding-cheatsheet, v0.1.0 (inactive)
language-gitignore, v0.2.0 (active)
language-javascript-jsx, v0.3.7 (active)
language-nunjucks, v4.1.0 (active)
language-svg, v0.9.0 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.16 (active)
linter-htmlhint, v1.3.0 (inactive)
linter-jshint, v2.1.0 (active)
linter-jsonlint, v1.3.0 (active)
linter-php, v1.2.0 (active)
linter-stylint, v2.2.2 (active)
linter-xo, v0.17.0 (active)
magic-tag, v0.2.3 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
minimap-bookmarks, v0.4.1 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.1.1 (active)
minimap-selection, v4.4.0 (active)
npm-outdated, v0.5.0 (inactive)
open-recent, v5.0.0 (active)
pigments, v0.34.0 (active)
pinned-tabs, v0.3.3 (active)
regex-railroad-diagram, v0.16.0 (active)
remember-file-positions, v0.2.2 (active)
remember-folds, v0.2.0 (active)
Remote-FTP, v0.8.8 (active)
resize-indent, v0.3.0 (active)
scroll-sync, v0.1.5 (inactive)
Stylus, v3.0.0 (active)
svg-preview, v0.9.0 (active)
sync-settings, v0.7.2 (active)
tab-close-shift-click, v1.0.2 (active)
tab-numbers, v0.5.0 (active)
terminal-plus, v0.14.5 (active)
todo-show, v1.7.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
tree-view-git-status, v1.1.0 (active)
w3c-validation, v0.4.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by shemerey** [comment]
save for me

**Comment by shemerey** [comment]
@forivall I think it's because of deprication, you can replace your `is editor` check with this one 

```javascript
To construct a text editor, use atom.workspace.buildTextEditor()
To check if an object is a text editor, use atom.workspace.isTextEditor(object)
```

**Comment by forivall** [comment]
fixed in https://github.com/forivall/atom-remember-folds/commit/924aefeb3054207045356d67cb0352dae8d1877e , new version released

**Comment by zenopopovici** [comment]
@forivall Thanks a lot for your work!
